import { join } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { Store } from '../src/requests/store.js';
import type { PrivateRequest } from '../src/requests/service.js';
import { exportBundle } from '../src/recognitium/evidence.js';
import { verifyOffline } from '../src/recognitium/evidence.js';
import type { Operation } from '../src/requests/journal.js';
const id = process.argv[2]; if (!id || !/^[a-zA-Z0-9_-]{1,80}$/.test(id)) throw new Error('Provide a safe request ID');
const root = process.argv.includes('--run') ? join('data','runs',id) : 'data';
const request = await new Store<PrivateRequest>(join(root,'requests')).read(id); if (!request) throw new Error('Unknown request');
const bundle = exportBundle(request);
const cycle = await new Store<{requestId:string;depositDrops:string;yield?:{realisedYieldDrops:string};refusal?:NonNullable<typeof bundle.nativeCycle>['refusal']}>(join(root,'cycles')).read('native');
if(!cycle?.yield || !cycle.refusal || cycle.requestId !== id) throw new Error('Complete native cycle with refusal and realised yield required');
const operations=await new Store<Operation>(join(root,'operations')).all();
bundle.nativeCycle={depositDrops:cycle.depositDrops,realisedYieldDrops:cycle.yield.realisedYieldDrops,refusal:cycle.refusal,
  transactions:Object.fromEntries(operations.filter(op=>op.result).map(op=>[op.id,op.result!]))};
verifyOffline(bundle);
await mkdir(join(root,'exports'),{recursive:true});
await writeFile(join(root,'exports',id+'.json'),JSON.stringify(bundle,null,2));
console.log(`Synthetic evidence exported to ${root}/exports/${id}.json. Review before publication.`);
