const $=id=>document.getElementById(id);let index=0,timer,data,checks=[];
function pause(){clearInterval(timer);timer=undefined;$('play').textContent='Play';}
function play(){if(index===data.scenes.length-1)index=0;render();$('play').textContent='Pause';timer=setInterval(()=>{index++;render();if(index===data.scenes.length-1)pause();},12000);}
function render(){const s=data.scenes[index];$('stage').textContent=`${index+1} / 5 · ${s.retrospective?'Retrospectively sealed evidence':'Original receipt'}`;$('title').textContent=s.title;$('amount').textContent=s.amount;$('copy').textContent=s.copy;$('setup').textContent=data.setup;
 $('ledger-title').textContent=s.resultCode??'Exact terms, before funding';$('ledger-info').textContent=s.ledgerIndex?`Validated ledger ${s.ledgerIndex} · network 4001 · fee ${s.feeDrops} drops`:'The agreement fingerprint will be covered by both LoanSet signatures.';$('tx').textContent=s.transactionHash??'';$('ledger-link').hidden=!s.transactionHash;if(s.transactionHash)$('ledger-link').href='https://custom.xrpl.org/lending-hackathon.dev.ripplex.io:51233/transactions/'+s.transactionHash;
 $('receipt-id').textContent=s.receiptId;$('hash').textContent=s.commitmentHash;$('receipt-link').href='https://www.recognitium.com/verify?id='+encodeURIComponent(s.receiptId);const c=checks.find(c=>c.receiptId===s.receiptId);$('receipt-status').textContent=c?.verified?'✓ Verified live with Recognitium':c?'Live check unavailable':'Checking receipt live…';$('seal-time').textContent=(s.retrospective?'Issued today for saved ledger evidence.':'Issued during the original loan workflow.')+(c?.verified?' Checked '+new Date(c.checkedAt).toLocaleTimeString('en-GB')+'.':'');
 $('count').textContent=`${index+1} / 5`;$('progress').value=index+1;$('back').disabled=index===0;$('next').disabled=index===4;[...$('timeline').children].forEach((e,i)=>e.classList.toggle('done',i<=index));$('scene').classList.remove('reveal');void $('scene').offsetWidth;$('scene').classList.add('reveal');}
try{const response=await fetch('/film-data.json');if(!response.ok)throw Error();data=await response.json();for(const _ of data.scenes)$('timeline').append(document.createElement('span'));render();play();
 $('play').onclick=()=>timer?pause():play();$('back').onclick=()=>{pause();index=Math.max(0,index-1);render();};$('next').onclick=()=>{pause();index=Math.min(4,index+1);render();};$('restart').onclick=()=>{pause();index=0;play();};$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
 fetch('/api/story-proof',{signal:AbortSignal.timeout(25000)}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(r=>{checks=r.receipts;render();}).catch(()=>{checks=data.scenes.map(s=>({receiptId:s.receiptId,verified:false}));render();});
}catch{$('title').textContent='Evidence could not be loaded.';$('copy').textContent='Reload the page. No execution or receipt issuance was attempted.';pause();}
