const esc=v=>String(v??'').replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';');
let context, data, requests=[], busy=false, message='',loaded=false;
const host=()=>document.getElementById('matching-workspace');
export function mountMarket(role,mode,requestId,hasRun=false){
 const unchanged=context?.role===role&&context?.mode===mode&&context?.requestId===requestId&&context?.hasRun===hasRun;
 context={role,mode,requestId,hasRun};
 let node=host();if(!node){node=document.createElement('section');node.id='matching-workspace';document.getElementById('overview-content').before(node);}
 node.hidden=mode!=='live';if(mode!=='live')return;
 if(!loaded){loaded=true;void refresh();}else if(!unchanged)paint();
}
async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(24000)});const v=await r.json();if(!r.ok)throw Error(v.error??'Connection unavailable');return v;}
async function refresh(){const before=JSON.stringify(data);const oldMessage=message;try{data=await api('/api/market');requests=data.eligibleRequests??[];message='';}catch(e){message=e.message;}if(before!==JSON.stringify(data)||oldMessage!==message||!host()?.querySelector('.card'))paint();}
async function send(body){if(busy)return;busy=true;message='Saving…';paint();try{data=await api('/api/market',body);requests=data.eligibleRequests??[];message='Saved. No money moved.';if(body.action==='match'){const url=new URL(location.href);url.searchParams.delete('new');url.searchParams.set('request',body.requestId);location.assign(url);}}catch(e){message=e.message;}finally{busy=false;paint();}}
function paint(){
 if(!host()||!context||context.mode!=='live')return;
 const role=context.role, now=Date.now();
 const offers=(data?.offers??[]).filter(o=>Date.parse(o.expiresAt)>now);
 const fresh=new URL(location.href).searchParams.get('new')==='1'&&!context.requestId;
 const matches=fresh?[]:(data?.matches??[]).filter(m=>!context.requestId||m.requestId===context.requestId);
 host().hidden=context.hasRun&&!matches.length;host().dataset.hasMatches=String(matches.length>0);host().dataset.hasRun=String(context.hasRun);
 const money=d=>(Number(d)/1000000).toLocaleString()+' test XRP';
 host().innerHTML='<div class="card"><p class="eyebrow">FIND · AGREE · REVIEW</p><h2>'+(role==='lender'?'Offer your availability':role==='borrower'?'Find a lender':'Review proposed matches')+'</h2><p>'+(role==='lender'?'Say how much you could lend. Nothing is transferred here.':role==='borrower'?'Your request and a lender’s availability come together before review.':'Check both approvals, then accept or decline the proposal.')+'</p>'+
 '<details><summary>IVM discovery and proof</summary><p>Operator-assisted IVM search for XRP returned no offers during this session on 13 September. This is a saved observation, not a live market feed.</p><p>Our approved demand was published at 11:39:48 Paris, expiry 12:09:48 Paris. A publication receipt does not prove a match.</p><a target="_blank" rel="noopener" href="https://api.recognitium.com/v1/verify/receipt/DG-572bb9f7ec7e41b888b3900147584189">Recognitium publication proof ↗</a><p>Availability below is shared local demo data, not an IVM publication. No wallet ownership or spendable balance has been verified.</p></details>'+
 (role==='lender'&&!matches.length?'<form id="availability-form"><label>Test wallet address<input name="account" required placeholder="r…" autocomplete="off"></label><label>Available XRP<input name="amount" type="number" min="1" max="10000" step="0.000001" required></label><label>Maximum loan duration (days)<input name="days" type="number" min="1" max="90" value="30" required></label><label><input name="confirmed" type="checkbox" required> I confirm this synthetic demo availability for 30 minutes.</label><button class="primary" '+(busy?'disabled':'')+'>Save availability</button></form>':'')+
 (role==='borrower'&&!matches.length?'<form id="match-form"><label>Your request<select name="request" required><option value="">Choose a request</option>'+requests.filter(r=>!['REJECTED','NEEDS_REVISION'].includes(r.status)).map(r=>'<option value="'+esc(r.clientRequestId)+'" '+(r.clientRequestId===context.requestId?'selected':'')+'>'+esc(r.clientRequestId.slice(8,16))+' · '+money(r.requestedDrops)+' · '+r.requestedDays+' days</option>').join('')+'</select></label><label>Lender availability<select name="offer" required><option value="">'+(offers.length?'Choose availability':'No availability yet')+'</option>'+offers.map(o=>'<option value="'+esc(o.id)+'">'+money(o.amountDrops)+' · up to '+o.maxDays+' days · '+esc(o.account.slice(0,8))+'…</option>').join('')+'</select></label><button class="primary" '+(busy||!offers.length?'disabled':'')+'>Propose match</button></form>':'')+
 '<p role="status">'+esc(message)+'</p><button data-market-refresh '+(busy?'disabled':'')+'>Refresh matches</button></div>'+
 matches.map(m=>{const expired=Date.parse(m.expiresAt)<=now;return '<article class="card match-card">'+progressBar(m,data.progress?.[m.requestId])+brikHistory(m)+ '<h3>'+money(m.amountDrops)+' · '+m.days+' days</h3><p>'+esc(data.progress?.[m.requestId]?.withdrawn?'Complete · money returned':data.progress?.[m.requestId]?.repaid?'Loan repaid':data.progress?.[m.requestId]?.funded?'Loan funded':expired?'Expired':m.decision==='accepted'?'Proposal accepted · execution still gated':m.decision==='declined'?'Proposal declined':m.receipt?'Ready for admin review':m.approvals.length===2?'Waiting for the match receipt':'Waiting for both parties')+'</p>'+(role==='broker'?checklist(m):'')+'<details><summary>Exact proposal</summary><p>Request '+esc(m.requestId)+'</p><p class="hash">Request fingerprint: '+esc(m.requestDigest)+'</p><p class="hash">Match fingerprint: '+esc(m.id)+'</p><p>Wallet: '+esc(m.availability.account)+'</p><p>Network 4001 · expires '+esc(new Date(m.expiresAt).toLocaleString())+'</p><p>This approves availability matching only. Interest, final loan terms, receipt issuance, verified liquidity and loan signatures remain separate. Demo roles are not authenticated identities.</p></details><details><summary>Balance and receipt evidence</summary><p>Ledger balance observed: '+money(m.balance.balanceDrops)+' at ledger '+m.balance.ledgerIndex+'. Funds are not reserved; fees and reserves still apply.</p><p>Match receipt: '+(m.receipt?'authority checked':'not issued')+'</p>'+ (m.receipt?'<a target="_blank" rel="noopener" href="https://api.recognitium.com/v1/verify/receipt/'+encodeURIComponent(m.receipt.receiptId)+'">Recognitium match proof ↗</a>':'') + (m.sealHash&&!m.receipt?'<details><summary>Seal this match through the operator</summary><p class="hash">'+esc(m.sealHash)+'</p><p>The operator seals this exact approval fingerprint through Recognitium MCP. Then attach its receipt ID; the server checks its authority and content.</p><form data-receipt="'+esc(m.id)+'"><input name="receiptId" placeholder="DG-…" required><button>Check receipt</button></form></details>':'') + '</details>'+(!expired&&m.decision==='pending'?(role==='broker'?'<button data-match="'+esc(m.id)+'" data-decision="accepted" '+(!data.checks?.[m.id]?.every(c=>c.ok)||busy?'disabled':'')+'>Accept proposal</button> <button data-match="'+esc(m.id)+'" data-decision="declined" '+(busy?'disabled':'')+'>Decline</button>':'<button data-match="'+esc(m.id)+'" data-decision="'+role+'" '+(m.approvals.includes(role)||busy?'disabled':'')+'>Approve this exact match</button>'):'')+'</article>';}).join('');
 host().querySelector('[data-market-refresh]').onclick=()=>void refresh();
 host().querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>void send({action:'decision',matchId:b.dataset.match,decision:b.dataset.decision}));
 host().querySelectorAll('[data-receipt]').forEach(f=>f.onsubmit=e=>{e.preventDefault();void send({action:'receipt',matchId:f.dataset.receipt,receiptId:new FormData(f).get('receiptId')});});
 const form=host().querySelector('#availability-form');if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);const amount=String(f.get('amount'));if(!/^\d+(\.\d{1,6})?$/.test(amount)){message='Use at most six decimal places.';paint();return;}const [whole,fraction='']=amount.split('.');void send({action:'offer',account:String(f.get('account')).trim(),amountDrops:String(BigInt(whole)*1000000n+BigInt(fraction.padEnd(6,'0'))),maxDays:Number(f.get('days')),expiresAt:new Date(Date.now()+1800000).toISOString(),confirm:f.get('confirmed')==='on'});};
 const match=host().querySelector('#match-form');if(match)match.onsubmit=e=>{e.preventDefault();const f=new FormData(match);void send({action:'match',requestId:f.get('request'),offerId:f.get('offer')});};
}

export function prepareAvailability(fields){const form=host()?.querySelector("#availability-form");if(!form)return;if(fields?.amount)form.elements.amount.value=fields.amount;if(fields?.days)form.elements.days.value=fields.days;form.scrollIntoView({behavior:"smooth",block:"center"});form.elements.account.focus();}

function progressBar(m,p={}){
 const steps=[['Matched',true],['Both approve',m.approvals.length===2],['Sealed',Boolean(m.receipt)],['Admin accepts',m.decision==='accepted'],['Funded',p.funded],['Repaid',p.repaid],['Returned',p.withdrawn]];
 const done=steps.filter(x=>x[1]).length;
 return '<div class="match-progress"><p>'+done+' of '+steps.length+' steps complete'+(m.decision==='declined'?' · Declined':'')+'</p><progress max="7" value="'+done+'" aria-label="Loan progress"></progress><ol>'+steps.map(([label,ok])=>'<li class="'+(ok?'complete':'')+'">'+(ok?'✓ ':'○ ')+label+'</li>').join('')+'</ol></div>';
}
function checklist(m){return '<ul class="match-checklist">'+(data.checks?.[m.id]??[]).map(c=>'<li><span aria-label="'+(c.ok?'passed':'missing')+'">'+(c.ok?'✓':'✕')+'</span> '+esc(c.label)+'</li>').join('')+'<li><span aria-label="missing">✕</span> KYC not provided · synthetic demo only</li></ul><details><summary>Identity and execution limits</summary><p>✕ KYC commitment not provided. Demo roles are not authenticated people. This synthetic demo permits proposal review only; it is not a real credit approval.</p><p>The ledger observation is historical, not a reservation. The native operator must control the matching lender wallet and obtain exact loan approvals before signing.</p></details>';}

setInterval(()=>{if(context?.mode==='live'&&!document.hidden&&!busy&&!document.activeElement?.closest('#matching-workspace form'))void refresh();},10000);

function brikHistory(m){
 const rows=[['1 · Lender availability',m.availability.id,'Saved · not individually sealed'],['2 · Borrower request',m.requestDigest,'Saved · not individually sealed'],['3 · Match + both approvals',m.sealHash??m.id,m.receipt?'Recognitium receipt verified':'Waiting for receipt'],['4 · Admin decision',m.decisionHash??'',m.decisionHash?'Saved · not individually sealed':'Waiting for review']];
 return '<details class="brik-history"><summary>Agreement briks · evidence history</summary><p>AI proposes. People approve. XRPL executes. A saved fingerprint becomes sealed only when its receipt is verified.</p><ol>'+rows.map(([name,hash,status])=>'<li><strong>'+name+'</strong><p>'+status+'</p>'+(hash?'<code class="hash">'+esc(hash)+'</code>':'')+'</li>').join('')+'</ol><p>The match binds the lender and borrower records. IVM publication and receipt verification remain distinct from XRPL funding.</p></details>';
}
